//
//  SettingsCloudPane.swift
//  Screendrop
//
//  Cloud settings: Worker URL + upload token configuration.
//  Files are uploaded directly to R2 via presigned URLs generated by the worker,
//  so users only need to configure the worker endpoint and token.
//

import AppKit
import SwiftUI

struct CloudSettingsPane: View {
    @State private var store = CloudCredentialStore.shared

    // Local form state (committed on save)
    @State private var workerURL = ""
    @State private var uploadToken = ""

    @State private var workerStatus: ConnectionStatus = .unchecked
    @State private var isLoading = true

    private var isWorkerConfigured: Bool {
        !workerURL.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        && !uploadToken.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var body: some View {
        Form {
            // MARK: - Worker Configuration

            Section("Screendrop Cloud") {
                TextField("Worker URL", text: $workerURL, prompt: Text("https://screendrop.your-name.workers.dev"))
                    .textFieldStyle(.roundedBorder)
                    .onChange(of: workerURL) { fieldDidChange() }

                SecureField("Upload Token", text: $uploadToken, prompt: Text("Paste your shared token"))
                    .textFieldStyle(.roundedBorder)
                    .onChange(of: uploadToken) { fieldDidChange() }

                HStack(spacing: 8) {
                    Button("Test Connection") {
                        Task { await testWorkerConnection() }
                    }
                    .controlSize(.small)
                    .disabled(!isWorkerConfigured)

                    connectionStatusIndicator(workerStatus)
                }
            }

            // MARK: - Setup Guide

            if !isWorkerConfigured {
                Section("Setup Guide") {
                    VStack(alignment: .leading, spacing: 10) {
                        SetupStepView(number: 1, text: "Deploy the Screendrop worker to Cloudflare Workers")
                        SetupStepView(number: 2, text: "Set UPLOAD_TOKEN secret: wrangler secret put UPLOAD_TOKEN")
                        SetupStepView(number: 3, text: "Set R2 credentials as secrets (R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY)")
                        SetupStepView(number: 4, text: "Paste your worker URL and upload token above")
                    }

                    Button("View on GitHub") {
                        if let url = URL(string: "https://github.com/fayazara/screendrop-worker") {
                            NSWorkspace.shared.open(url)
                        }
                    }
                    .controlSize(.small)
                }
            }
        }
        .formStyle(.grouped)
        .contentMargins(.top, 8, for: .scrollContent)
        .toolbar {
            ToolbarItem(placement: .automatic) {
                HStack(spacing: 6) {
                    Circle()
                        .fill(overallStatusColor)
                        .frame(width: 7, height: 7)

                    Text(overallStatusText)
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 10)
                .padding(.vertical, 4)
            }
        }
        .onAppear {
            loadFromStore()
        }
        .task {
            if isWorkerConfigured {
                await testWorkerConnection()
            }
        }
    }

    // MARK: - Helpers

    private func loadFromStore() {
        isLoading = true
        workerURL = store.workerURL
        uploadToken = store.uploadToken
        DispatchQueue.main.async {
            isLoading = false
        }
    }

    private func fieldDidChange() {
        guard !isLoading else { return }
        workerStatus = .unchecked
        saveSettings()
    }

    private func saveSettings() {
        store.workerURL = workerURL.trimmingCharacters(in: .whitespacesAndNewlines)
        store.uploadToken = uploadToken.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - Connection Test

    private func testWorkerConnection() async {
        saveSettings()
        workerStatus = .checking

        let raw = workerURL
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
        let base = raw.lowercased().hasPrefix("http") ? raw : "https://\(raw)"
        let token = uploadToken.trimmingCharacters(in: .whitespacesAndNewlines)

        guard let url = URL(string: "\(base)/api/ping") else {
            workerStatus = .failed("Invalid URL")
            return
        }

        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 10
        request.setValue("Bearer \(token)", forHTTPHeaderField: "Authorization")

        do {
            let (_, response) = try await URLSession.shared.data(for: request)
            guard let http = response as? HTTPURLResponse else {
                workerStatus = .failed("No response")
                return
            }

            switch http.statusCode {
            case 200:
                workerStatus = .connected
            case 401, 403:
                workerStatus = .failed("Invalid token")
            default:
                workerStatus = .failed("HTTP \(http.statusCode)")
            }
        } catch {
            workerStatus = .failed(error.localizedDescription)
        }
    }

    // MARK: - Status Display

    private var overallStatusColor: Color {
        if isWorkerConfigured {
            if workerStatus == .connected {
                return .green
            }
            return .orange
        }
        return .gray
    }

    private var overallStatusText: String {
        if !isWorkerConfigured {
            return "Not configured"
        }
        if workerStatus == .connected {
            return "Connected"
        }
        return "Not verified"
    }

    @ViewBuilder
    private func connectionStatusIndicator(_ status: ConnectionStatus) -> some View {
        switch status {
        case .unchecked:
            EmptyView()
        case .checking:
            ProgressView()
                .scaleEffect(0.6)
                .frame(width: 16, height: 16)
        case .connected:
            Image(systemName: "checkmark.circle.fill")
                .foregroundStyle(.green)
                .font(.system(size: 13))
        case .failed(let message):
            HStack(spacing: 4) {
                Image(systemName: "xmark.circle.fill")
                    .foregroundStyle(.red)
                    .font(.system(size: 13))
                Text(message)
                    .font(.system(size: 11))
                    .foregroundStyle(.red)
                    .lineLimit(1)
            }
        }
    }
}

private enum ConnectionStatus: Equatable {
    case unchecked
    case checking
    case connected
    case failed(String)
}

private struct SetupStepView: View {
    let number: Int
    let text: String

    var body: some View {
        HStack(alignment: .top, spacing: 10) {
            Text("\(number)")
                .font(.system(size: 11, weight: .bold, design: .rounded))
                .foregroundStyle(.white)
                .frame(width: 20, height: 20)
                .background(Circle().fill(.tertiary))

            Text(text)
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
                .lineSpacing(2)
        }
    }
}
